-- PostgreSQL: Figma OAuth tokens captured during student registration (before a board exists).
-- Mirrors EF migration 20260407083621_AddFigmaOAuthPendingTable (table + unique email index).

CREATE TABLE IF NOT EXISTS "FigmaOAuthPending" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(255) NOT NULL,
    "FigmaAccessToken" character varying(512),
    "FigmaRefreshToken" character varying(512),
    "FigmaTokenExpiry" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_FigmaOAuthPending" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_FigmaOAuthPending_Email"
    ON "FigmaOAuthPending" ("Email");
