// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using strAppersBackend.Data;

#nullable disable

namespace strAppersBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126121953_AddProjectCriteriaTableAndCriteri")]
    partial class AddProjectCriteriaTableAndCriteri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("strAppersBackend.Models.DesignVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DesignDocument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DesignDocumentPdf")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionNumber");

                    b.ToTable("DesignVersions");
                });

            modelBuilder.Entity("strAppersBackend.Models.Figma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("BoardId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FigmaAccessToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("FigmaAccessToken");

                    b.Property<string>("FigmaFileKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("FigmaFileKey");

                    b.Property<string>("FigmaFileUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("FigmaFileUrl");

                    b.Property<DateTime?>("FigmaLastSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FigmaLastSync");

                    b.Property<string>("FigmaRefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("FigmaRefreshToken");

                    b.Property<DateTime?>("FigmaTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FigmaTokenExpiry");

                    b.Property<string>("FigmaUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("FigmaUserId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("FigmaFileKey")
                        .IsUnique();

                    b.ToTable("Figma");
                });

            modelBuilder.Entity("strAppersBackend.Models.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Added")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StudentFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Added");

                    b.HasIndex("ChannelId");

                    b.HasIndex("JoinDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StudentEmail");

                    b.HasIndex("StudentId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("strAppersBackend.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(4034),
                            Department = "Computer Science",
                            Description = "Study of computational systems and design",
                            IsActive = true,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(4047),
                            Department = "Computer Science",
                            Description = "Engineering approach to software development",
                            IsActive = true,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(4050),
                            Department = "Computer Science",
                            Description = "Extracting insights from data",
                            IsActive = true,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(4052),
                            Department = "Computer Science",
                            Description = "Protecting digital systems and data",
                            IsActive = true,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(4055),
                            Department = "Information Systems",
                            Description = "Management and use of technology",
                            IsActive = true,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(4057),
                            Department = "Business",
                            Description = "General business management",
                            IsActive = true,
                            Name = "Business Administration"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.ModuleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ModuleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Authentication"
                        },
                        new
                        {
                            Id = 5,
                            Name = "API"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 7,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Testing"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TermsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TermsUse")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tech Street, Tech City",
                            ContactEmail = "info@techuniversity.edu",
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(8556),
                            Description = "Leading technology university",
                            IsActive = true,
                            Name = "Tech University",
                            Phone = "555-0101",
                            TermsAccepted = false,
                            Type = "University",
                            Website = "https://techuniversity.edu"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Innovation Ave, Tech City",
                            ContactEmail = "contact@innovationlabs.com",
                            CreatedAt = new DateTime(2025, 10, 2, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(8566),
                            Description = "Research and development company",
                            IsActive = true,
                            Name = "Innovation Labs",
                            Phone = "555-0102",
                            TermsAccepted = false,
                            Type = "Company",
                            Website = "https://innovationlabs.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Good Street, Tech City",
                            ContactEmail = "hello@codeforgood.org",
                            CreatedAt = new DateTime(2025, 10, 7, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(8569),
                            Description = "Non-profit organization promoting tech for social good",
                            IsActive = true,
                            Name = "Code for Good",
                            Phone = "555-0103",
                            TermsAccepted = false,
                            Type = "Non-profit",
                            Website = "https://codeforgood.org"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Creator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammingLanguages");
                });

            modelBuilder.Entity("strAppersBackend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedChunks")
                        .HasColumnType("integer")
                        .HasColumnName("completed_chunks");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CriteriaIds")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CriteriaIds");

                    b.Property<string>("DataSchema")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentManifest")
                        .HasColumnType("TEXT")
                        .HasColumnName("deployment_manifest");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExtendedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeGenerationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ide_generation_status");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isAvailable");

                    b.Property<bool?>("Kickoff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Kickoff");

                    b.Property<int>("MockRecordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("mock_records_count");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SystemDesign")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SystemDesignDoc")
                        .HasColumnType("bytea");

                    b.Property<string>("SystemDesignFormatted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("SystemDesignFormatted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer")
                        .HasColumnName("total_chunks");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 10, 27, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4118),
                            Description = "Web application for managing student records and academic progress",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 1,
                            Priority = "High",
                            Title = "Student Management System",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 2,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 6, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4129),
                            Description = "Machine learning platform for academic research",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 2,
                            Priority = "Medium",
                            Title = "AI Research Platform",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 3,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 8, 28, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4134),
                            Description = "Mobile app connecting volunteers with local community needs",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 3,
                            Priority = "High",
                            Title = "Community Outreach App",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 4,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 11, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4138),
                            Description = "E-learning platform with video streaming and assessments",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 1,
                            Priority = "Critical",
                            Title = "Online Learning Platform",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 5,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 16, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4141),
                            Description = "Real-time dashboard for analyzing student performance metrics",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 1,
                            Priority = "Medium",
                            Title = "Data Analytics Dashboard",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 6,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 21, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4144),
                            Description = "Mobile application for students to discover and register for campus events",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 1,
                            Priority = "Medium",
                            Title = "Mobile App for Campus Events",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 7,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 23, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4147),
                            Description = "VR environment for immersive learning experiences",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 2,
                            Priority = "High",
                            Title = "Virtual Reality Learning Lab",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 8,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 25, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4151),
                            Description = "Secure voting system using blockchain technology",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 1,
                            Priority = "High",
                            Title = "Blockchain Voting System",
                            TotalChunks = 0
                        },
                        new
                        {
                            Id = 9,
                            CompletedChunks = 0,
                            CreatedAt = new DateTime(2025, 11, 24, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(4155),
                            Description = "Internet of Things system for campus management",
                            IdeGenerationStatus = "not_started",
                            IsAvailable = true,
                            Kickoff = false,
                            MockRecordsCount = 10,
                            OrganizationId = 2,
                            Priority = "Medium",
                            Title = "IoT Smart Campus",
                            TotalChunks = 0
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("BoardId");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("AdminId");

                    b.Property<string>("BoardUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("BoardURL");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DueDate");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("GithubUrl");

                    b.Property<string>("GroupChat")
                        .HasColumnType("text")
                        .HasColumnName("GroupChat");

                    b.Property<string>("MovieUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MovieUrl");

                    b.Property<DateTime?>("NextMeetingTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NextMeetingTime");

                    b.Property<string>("NextMeetingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("NextMeetingUrl");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectId");

                    b.Property<string>("PublishUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("PublishUrl");

                    b.Property<string>("SprintPlan")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProjectBoards");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ProjectCriterias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Popular Projects"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UI/UX Designer Needed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Backend Developer Needed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Frontend Developer Needed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product manager Needed"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marketing Needed"
                        },
                        new
                        {
                            Id = 7,
                            Name = "New Projects"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int?>("ModuleType")
                        .HasColumnType("integer")
                        .HasColumnName("ModuleType");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectId");

                    b.Property<int?>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("Sequence");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("ModuleType");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Sequence");

                    b.ToTable("ProjectModules");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(9831),
                            Description = "Newly created project",
                            IsActive = true,
                            Name = "New",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(9835),
                            Description = "Project in planning phase",
                            IsActive = true,
                            Name = "Planning",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(9838),
                            Description = "Project currently being worked on",
                            IsActive = true,
                            Name = "In Progress",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(9841),
                            Description = "Project temporarily paused",
                            IsActive = true,
                            Name = "On Hold",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#059669",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(9843),
                            Description = "Project successfully completed",
                            IsActive = true,
                            Name = "Completed",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#6B7280",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(9845),
                            Description = "Project cancelled or abandoned",
                            IsActive = true,
                            Name = "Cancelled",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectsIDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChunkDescription")
                        .HasColumnType("text")
                        .HasColumnName("chunk_description");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chunk_id");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chunk_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string[]>("Dependencies")
                        .HasColumnType("text[]")
                        .HasColumnName("dependencies");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FilesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("files_count");

                    b.Property<string>("FilesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("files_json");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("GenerationOrder")
                        .HasColumnType("integer")
                        .HasColumnName("generation_order");

                    b.Property<int?>("GenerationTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("generation_time_ms");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id");

                    b.HasIndex("GenerationOrder");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "ChunkId")
                        .IsUnique();

                    b.ToTable("ProjectsIDE", (string)null);
                });

            modelBuilder.Entity("strAppersBackend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Leadership",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6131),
                            Description = "Leads project planning and execution",
                            IsActive = true,
                            Name = "Project Manager",
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6141),
                            Description = "Develops user interface and user experience",
                            IsActive = true,
                            Name = "Frontend Developer",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6143),
                            Description = "Develops server-side logic and database integration",
                            IsActive = true,
                            Name = "Backend Developer",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6146),
                            Description = "Designs user interface and user experience",
                            IsActive = true,
                            Name = "UI/UX Designer",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6148),
                            Description = "Tests software and ensures quality standards",
                            IsActive = true,
                            Name = "Quality Assurance",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "Leadership",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6151),
                            Description = "Provides guidance and mentorship to team members",
                            IsActive = true,
                            Name = "Team Lead",
                            Type = 4
                        },
                        new
                        {
                            Id = 7,
                            Category = "Academic",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6153),
                            Description = "Conducts research and data analysis",
                            IsActive = true,
                            Name = "Research Assistant",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Administrative",
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 169, DateTimeKind.Utc).AddTicks(6156),
                            Description = "Creates and maintains project documentation",
                            IsActive = true,
                            Name = "Documentation Specialist",
                            Type = 2
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GithubUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("Photo");

                    b.Property<int?>("ProgrammingLanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("ProgrammingLanguageId");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectPriority1")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectPriority2")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectPriority3")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectPriority4")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartPendingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MajorId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectPriority1");

                    b.HasIndex("ProjectPriority2");

                    b.HasIndex("ProjectPriority3");

                    b.HasIndex("ProjectPriority4");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("YearId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 12, 12, 19, 52, 168, DateTimeKind.Utc).AddTicks(8232),
                            Email = "alex.johnson@techuniversity.edu",
                            FirstName = "Alex",
                            GithubUser = "",
                            IsAdmin = true,
                            IsAvailable = true,
                            LastName = "Johnson",
                            LinkedInUrl = "https://linkedin.com/in/alexjohnson",
                            MajorId = 1,
                            StudentId = "TU001",
                            YearId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 17, 12, 19, 52, 168, DateTimeKind.Utc).AddTicks(8242),
                            Email = "sarah.williams@techuniversity.edu",
                            FirstName = "Sarah",
                            GithubUser = "",
                            IsAdmin = false,
                            IsAvailable = true,
                            LastName = "Williams",
                            LinkedInUrl = "https://linkedin.com/in/sarahwilliams",
                            MajorId = 2,
                            StudentId = "TU002",
                            YearId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 22, 12, 19, 52, 168, DateTimeKind.Utc).AddTicks(8245),
                            Email = "michael.brown@techuniversity.edu",
                            FirstName = "Michael",
                            GithubUser = "",
                            IsAdmin = true,
                            IsAvailable = true,
                            LastName = "Brown",
                            LinkedInUrl = "https://linkedin.com/in/michaelbrown",
                            MajorId = 3,
                            StudentId = "TU003",
                            YearId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 27, 12, 19, 52, 168, DateTimeKind.Utc).AddTicks(8249),
                            Email = "emily.davis@techuniversity.edu",
                            FirstName = "Emily",
                            GithubUser = "",
                            IsAdmin = false,
                            IsAvailable = true,
                            LastName = "Davis",
                            LinkedInUrl = "https://linkedin.com/in/emilydavis",
                            MajorId = 4,
                            StudentId = "TU004",
                            YearId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 19, 52, 168, DateTimeKind.Utc).AddTicks(8252),
                            Email = "david.miller@techuniversity.edu",
                            FirstName = "David",
                            GithubUser = "",
                            IsAdmin = false,
                            IsAvailable = true,
                            LastName = "Miller",
                            LinkedInUrl = "https://linkedin.com/in/davidmiller",
                            MajorId = 1,
                            StudentId = "TU005",
                            YearId = 1
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.StudentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDate = new DateTime(2025, 10, 27, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1413),
                            IsActive = true,
                            Notes = "Leading the Student Management System project",
                            RoleId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedDate = new DateTime(2025, 11, 1, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1419),
                            IsActive = true,
                            Notes = "Frontend development for multiple projects",
                            RoleId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedDate = new DateTime(2025, 11, 6, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1425),
                            IsActive = true,
                            Notes = "Backend development and database design",
                            RoleId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            AssignedDate = new DateTime(2025, 11, 11, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1428),
                            IsActive = true,
                            Notes = "UI/UX design for community outreach app",
                            RoleId = 4,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            AssignedDate = new DateTime(2025, 11, 16, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1430),
                            IsActive = true,
                            Notes = "QA testing for online learning platform",
                            RoleId = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            AssignedDate = new DateTime(2025, 10, 22, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1432),
                            IsActive = true,
                            Notes = "Team lead for junior developers",
                            RoleId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedDate = new DateTime(2025, 11, 8, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1434),
                            IsActive = true,
                            Notes = "Research on AI and machine learning",
                            RoleId = 7,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            AssignedDate = new DateTime(2025, 11, 14, 12, 19, 52, 170, DateTimeKind.Utc).AddTicks(1436),
                            IsActive = true,
                            Notes = "Documentation for frontend components",
                            RoleId = 8,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(5526),
                            Description = "First year of study",
                            IsActive = true,
                            Name = "Freshman",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(5532),
                            Description = "Second year of study",
                            IsActive = true,
                            Name = "Sophomore",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(5593),
                            Description = "Third year of study",
                            IsActive = true,
                            Name = "Junior",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(5596),
                            Description = "Fourth year of study",
                            IsActive = true,
                            Name = "Senior",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 19, 52, 159, DateTimeKind.Utc).AddTicks(5598),
                            Description = "Graduate level study",
                            IsActive = true,
                            Name = "Graduate",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.DesignVersion", b =>
                {
                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany("DesignVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("strAppersBackend.Models.Figma", b =>
                {
                    b.HasOne("strAppersBackend.Models.ProjectBoard", "ProjectBoard")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectBoard");
                });

            modelBuilder.Entity("strAppersBackend.Models.JoinRequest", b =>
                {
                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("strAppersBackend.Models.Project", b =>
                {
                    b.HasOne("strAppersBackend.Models.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectBoard", b =>
                {
                    b.HasOne("strAppersBackend.Models.Student", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.ProjectStatus", "Status")
                        .WithMany("ProjectBoards")
                        .HasForeignKey("StatusId");

                    b.Navigation("Admin");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectModule", b =>
                {
                    b.HasOne("strAppersBackend.Models.ModuleType", "ModuleTypeNavigation")
                        .WithMany("ProjectModules")
                        .HasForeignKey("ModuleType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ModuleTypeNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectsIDE", b =>
                {
                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany("IDEChunks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("strAppersBackend.Models.Student", b =>
                {
                    b.HasOne("strAppersBackend.Models.ProjectBoard", "ProjectBoard")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("Students")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Project", "ProjectPriority1Project")
                        .WithMany()
                        .HasForeignKey("ProjectPriority1")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Project", "ProjectPriority2Project")
                        .WithMany()
                        .HasForeignKey("ProjectPriority2")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Project", "ProjectPriority3Project")
                        .WithMany()
                        .HasForeignKey("ProjectPriority3")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Project", "ProjectPriority4Project")
                        .WithMany()
                        .HasForeignKey("ProjectPriority4")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Year", "Year")
                        .WithMany("Students")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("ProgrammingLanguage");

                    b.Navigation("Project");

                    b.Navigation("ProjectBoard");

                    b.Navigation("ProjectPriority1Project");

                    b.Navigation("ProjectPriority2Project");

                    b.Navigation("ProjectPriority3Project");

                    b.Navigation("ProjectPriority4Project");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("strAppersBackend.Models.StudentRole", b =>
                {
                    b.HasOne("strAppersBackend.Models.Role", "Role")
                        .WithMany("StudentRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.Student", "Student")
                        .WithMany("StudentRoles")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("strAppersBackend.Models.Major", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("strAppersBackend.Models.ModuleType", b =>
                {
                    b.Navigation("ProjectModules");
                });

            modelBuilder.Entity("strAppersBackend.Models.Organization", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProgrammingLanguage", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("strAppersBackend.Models.Project", b =>
                {
                    b.Navigation("DesignVersions");

                    b.Navigation("IDEChunks");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectStatus", b =>
                {
                    b.Navigation("ProjectBoards");
                });

            modelBuilder.Entity("strAppersBackend.Models.Role", b =>
                {
                    b.Navigation("StudentRoles");
                });

            modelBuilder.Entity("strAppersBackend.Models.Student", b =>
                {
                    b.Navigation("StudentRoles");
                });

            modelBuilder.Entity("strAppersBackend.Models.Year", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
