// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using strAppersBackend.Data;

#nullable disable

namespace strAppersBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250915071923_AddExtendedDescriptionFieldOnly")]
    partial class AddExtendedDescriptionFieldOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("strAppersBackend.Models.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Added")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StudentFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Added");

                    b.HasIndex("ChannelId");

                    b.HasIndex("JoinDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StudentEmail");

                    b.HasIndex("StudentId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("strAppersBackend.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(106),
                            Department = "Computer Science",
                            Description = "Study of computational systems and design",
                            IsActive = true,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(120),
                            Department = "Computer Science",
                            Description = "Engineering approach to software development",
                            IsActive = true,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(123),
                            Department = "Computer Science",
                            Description = "Extracting insights from data",
                            IsActive = true,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(125),
                            Department = "Computer Science",
                            Description = "Protecting digital systems and data",
                            IsActive = true,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(127),
                            Department = "Information Systems",
                            Description = "Management and use of technology",
                            IsActive = true,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(130),
                            Department = "Business",
                            Description = "General business management",
                            IsActive = true,
                            Name = "Business Administration"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tech Street, Tech City",
                            ContactEmail = "info@techuniversity.edu",
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(2736),
                            Description = "Leading technology university",
                            IsActive = true,
                            Name = "Tech University",
                            Phone = "555-0101",
                            Type = "University",
                            Website = "https://techuniversity.edu"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Innovation Ave, Tech City",
                            ContactEmail = "contact@innovationlabs.com",
                            CreatedAt = new DateTime(2025, 7, 22, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(2742),
                            Description = "Research and development company",
                            IsActive = true,
                            Name = "Innovation Labs",
                            Phone = "555-0102",
                            Type = "Company",
                            Website = "https://innovationlabs.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Good Street, Tech City",
                            ContactEmail = "hello@codeforgood.org",
                            CreatedAt = new DateTime(2025, 7, 27, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(2746),
                            Description = "Non-profit organization promoting tech for social good",
                            IsActive = true,
                            Name = "Code for Good",
                            Phone = "555-0103",
                            Type = "Non-profit",
                            Website = "https://codeforgood.org"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtendedDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAdmin")
                        .HasColumnType("boolean");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 16, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9977),
                            Description = "Web application for managing student records and academic progress",
                            DueDate = new DateTime(2025, 10, 15, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9973),
                            HasAdmin = true,
                            OrganizationId = 1,
                            Priority = "High",
                            StartDate = new DateTime(2025, 8, 16, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9961),
                            StatusId = 3,
                            Title = "Student Management System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 26, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9983),
                            Description = "Machine learning platform for academic research",
                            DueDate = new DateTime(2025, 11, 14, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9982),
                            HasAdmin = false,
                            OrganizationId = 2,
                            Priority = "Medium",
                            StartDate = new DateTime(2025, 8, 26, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9981),
                            StatusId = 2,
                            Title = "AI Research Platform"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 17, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9988),
                            Description = "Mobile app connecting volunteers with local community needs",
                            EndDate = new DateTime(2025, 9, 5, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9987),
                            HasAdmin = true,
                            OrganizationId = 3,
                            Priority = "High",
                            StartDate = new DateTime(2025, 6, 17, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9986),
                            StatusId = 5,
                            Title = "Community Outreach App"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 31, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9993),
                            Description = "E-learning platform with video streaming and assessments",
                            DueDate = new DateTime(2025, 10, 30, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9992),
                            HasAdmin = false,
                            OrganizationId = 1,
                            Priority = "Critical",
                            StartDate = new DateTime(2025, 8, 31, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9991),
                            StatusId = 3,
                            Title = "Online Learning Platform"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 5, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9997),
                            Description = "Real-time dashboard for analyzing student performance metrics",
                            HasAdmin = false,
                            OrganizationId = 1,
                            Priority = "Medium",
                            StartDate = new DateTime(2025, 9, 5, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(9996),
                            StatusId = 4,
                            Title = "Data Analytics Dashboard"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 10, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(2),
                            Description = "Mobile application for students to discover and register for campus events",
                            DueDate = new DateTime(2025, 11, 14, 7, 19, 22, 263, DateTimeKind.Utc),
                            HasAdmin = false,
                            OrganizationId = 1,
                            Priority = "Medium",
                            StartDate = new DateTime(2025, 9, 10, 7, 19, 22, 263, DateTimeKind.Utc),
                            StatusId = 1,
                            Title = "Mobile App for Campus Events"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 12, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(7),
                            Description = "VR environment for immersive learning experiences",
                            DueDate = new DateTime(2025, 12, 14, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5),
                            HasAdmin = false,
                            OrganizationId = 2,
                            Priority = "High",
                            StartDate = new DateTime(2025, 9, 12, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(4),
                            StatusId = 1,
                            Title = "Virtual Reality Learning Lab"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 14, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(11),
                            Description = "Secure voting system using blockchain technology",
                            DueDate = new DateTime(2025, 11, 29, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(10),
                            HasAdmin = false,
                            OrganizationId = 1,
                            Priority = "High",
                            StartDate = new DateTime(2025, 9, 14, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(9),
                            StatusId = 1,
                            Title = "Blockchain Voting System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 13, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(15),
                            Description = "Internet of Things system for campus management",
                            DueDate = new DateTime(2026, 1, 13, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(14),
                            HasAdmin = false,
                            OrganizationId = 2,
                            Priority = "Medium",
                            StartDate = new DateTime(2025, 9, 13, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(13),
                            StatusId = 1,
                            Title = "IoT Smart Campus"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(3759),
                            Description = "Newly created project",
                            IsActive = true,
                            Name = "New",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(3765),
                            Description = "Project in planning phase",
                            IsActive = true,
                            Name = "Planning",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(3768),
                            Description = "Project currently being worked on",
                            IsActive = true,
                            Name = "In Progress",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(3771),
                            Description = "Project temporarily paused",
                            IsActive = true,
                            Name = "On Hold",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#059669",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(3773),
                            Description = "Project successfully completed",
                            IsActive = true,
                            Name = "Completed",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#6B7280",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(3776),
                            Description = "Project cancelled or abandoned",
                            IsActive = true,
                            Name = "Cancelled",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Leadership",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1272),
                            Description = "Leads project planning and execution",
                            IsActive = true,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1278),
                            Description = "Develops user interface and user experience",
                            IsActive = true,
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1281),
                            Description = "Develops server-side logic and database integration",
                            IsActive = true,
                            Name = "Backend Developer"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1283),
                            Description = "Designs user interface and user experience",
                            IsActive = true,
                            Name = "UI/UX Designer"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Technical",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1286),
                            Description = "Tests software and ensures quality standards",
                            IsActive = true,
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Leadership",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1288),
                            Description = "Provides guidance and mentorship to team members",
                            IsActive = true,
                            Name = "Team Lead"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Academic",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1290),
                            Description = "Conducts research and data analysis",
                            IsActive = true,
                            Name = "Research Assistant"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Administrative",
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(1293),
                            Description = "Creates and maintains project documentation",
                            IsActive = true,
                            Name = "Documentation Specialist"
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MajorId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("YearId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 1, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(3949),
                            Email = "alex.johnson@techuniversity.edu",
                            FirstName = "Alex",
                            IsAdmin = true,
                            LastName = "Johnson",
                            LinkedInUrl = "https://linkedin.com/in/alexjohnson",
                            MajorId = 1,
                            OrganizationId = 1,
                            ProjectId = 1,
                            StudentId = "TU001",
                            YearId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 6, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(3960),
                            Email = "sarah.williams@techuniversity.edu",
                            FirstName = "Sarah",
                            IsAdmin = false,
                            LastName = "Williams",
                            LinkedInUrl = "https://linkedin.com/in/sarahwilliams",
                            MajorId = 2,
                            OrganizationId = 1,
                            ProjectId = 2,
                            StudentId = "TU002",
                            YearId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 11, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(3964),
                            Email = "michael.brown@techuniversity.edu",
                            FirstName = "Michael",
                            IsAdmin = true,
                            LastName = "Brown",
                            LinkedInUrl = "https://linkedin.com/in/michaelbrown",
                            MajorId = 3,
                            OrganizationId = 1,
                            ProjectId = 3,
                            StudentId = "TU003",
                            YearId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 16, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(3967),
                            Email = "emily.davis@techuniversity.edu",
                            FirstName = "Emily",
                            IsAdmin = false,
                            LastName = "Davis",
                            LinkedInUrl = "https://linkedin.com/in/emilydavis",
                            MajorId = 4,
                            OrganizationId = 1,
                            StudentId = "TU004",
                            YearId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 21, 7, 19, 22, 262, DateTimeKind.Utc).AddTicks(3971),
                            Email = "david.miller@techuniversity.edu",
                            FirstName = "David",
                            IsAdmin = false,
                            LastName = "Miller",
                            LinkedInUrl = "https://linkedin.com/in/davidmiller",
                            MajorId = 1,
                            OrganizationId = 1,
                            StudentId = "TU005",
                            YearId = 1
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.StudentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDate = new DateTime(2025, 8, 16, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5178),
                            IsActive = true,
                            Notes = "Leading the Student Management System project",
                            RoleId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedDate = new DateTime(2025, 8, 21, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5186),
                            IsActive = true,
                            Notes = "Frontend development for multiple projects",
                            RoleId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedDate = new DateTime(2025, 8, 26, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5189),
                            IsActive = true,
                            Notes = "Backend development and database design",
                            RoleId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            AssignedDate = new DateTime(2025, 8, 31, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5192),
                            IsActive = true,
                            Notes = "UI/UX design for community outreach app",
                            RoleId = 4,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            AssignedDate = new DateTime(2025, 9, 5, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5194),
                            IsActive = true,
                            Notes = "QA testing for online learning platform",
                            RoleId = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            AssignedDate = new DateTime(2025, 8, 11, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5196),
                            IsActive = true,
                            Notes = "Team lead for junior developers",
                            RoleId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedDate = new DateTime(2025, 8, 28, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5199),
                            IsActive = true,
                            Notes = "Research on AI and machine learning",
                            RoleId = 7,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            AssignedDate = new DateTime(2025, 9, 3, 7, 19, 22, 263, DateTimeKind.Utc).AddTicks(5201),
                            IsActive = true,
                            Notes = "Documentation for frontend components",
                            RoleId = 8,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(1326),
                            Description = "First year of study",
                            IsActive = true,
                            Name = "Freshman",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(1331),
                            Description = "Second year of study",
                            IsActive = true,
                            Name = "Sophomore",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(1334),
                            Description = "Third year of study",
                            IsActive = true,
                            Name = "Junior",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(1336),
                            Description = "Fourth year of study",
                            IsActive = true,
                            Name = "Senior",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 17, 7, 19, 22, 261, DateTimeKind.Utc).AddTicks(1338),
                            Description = "Graduate level study",
                            IsActive = true,
                            Name = "Graduate",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("strAppersBackend.Models.JoinRequest", b =>
                {
                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("strAppersBackend.Models.Project", b =>
                {
                    b.HasOne("strAppersBackend.Models.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.ProjectStatus", "Status")
                        .WithMany("Projects")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("strAppersBackend.Models.Student", b =>
                {
                    b.HasOne("strAppersBackend.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.Organization", "Organization")
                        .WithMany("Students")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Project", "Project")
                        .WithMany("Students")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("strAppersBackend.Models.Year", "Year")
                        .WithMany("Students")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Organization");

                    b.Navigation("Project");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("strAppersBackend.Models.StudentRole", b =>
                {
                    b.HasOne("strAppersBackend.Models.Role", "Role")
                        .WithMany("StudentRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("strAppersBackend.Models.Student", "Student")
                        .WithMany("StudentRoles")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("strAppersBackend.Models.Major", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("strAppersBackend.Models.Organization", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("strAppersBackend.Models.Project", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("strAppersBackend.Models.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("strAppersBackend.Models.Role", b =>
                {
                    b.Navigation("StudentRoles");
                });

            modelBuilder.Entity("strAppersBackend.Models.Student", b =>
                {
                    b.Navigation("StudentRoles");
                });

            modelBuilder.Entity("strAppersBackend.Models.Year", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
