-- =============================================================================
-- Agent exercises: project personas + scenario-based grading  (PostgreSQL)
--
-- 1 new column on an existing table, 9 new tables. No existing column changes.
-- Safe to re-run: every statement is guarded.
-- Behaviour is unchanged until rows are added: a NULL InstituteProjects.MainAIPersonaId
-- falls back to the institute's persona exactly as today, and projects with no
-- InstituteProjectPersonas rows show only the existing chat.
--
-- Matches the hand-written EF migration AddAgentExercisesAndProjectPersonas.
-- Rollback: section R at the bottom (commented out).
-- =============================================================================

BEGIN;

-- 1. InstituteProjects.MainAIPersonaId  (project-level override of the institute persona)
ALTER TABLE "InstituteProjects"
    ADD COLUMN IF NOT EXISTS "MainAIPersonaId" integer NULL;

CREATE INDEX IF NOT EXISTS "IX_InstituteProjects_MainAIPersonaId"
    ON "InstituteProjects" ("MainAIPersonaId");

-- ON DELETE SET NULL: deleting a persona drops the project back to the institute persona.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_InstituteProjects_AIPersonas_MainAIPersonaId') THEN
        ALTER TABLE "InstituteProjects"
            ADD CONSTRAINT "FK_InstituteProjects_AIPersonas_MainAIPersonaId"
            FOREIGN KEY ("MainAIPersonaId") REFERENCES "AIPersonas" ("Id") ON DELETE SET NULL;
    END IF;
END $$;


-- 2. InstituteProjectPersonas  (side personas: supporting roles, not assessed)
CREATE TABLE IF NOT EXISTS "InstituteProjectPersonas" (
    "Id"                 integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "InstituteProjectId" integer NOT NULL,
    "PersonaId"          integer NOT NULL,
    "ContextText"        text NULL,
    "SortOrder"          integer NOT NULL DEFAULT 0,
    "CreatedAt"          timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_InstituteProjectPersonas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InstituteProjectPersonas_InstituteProjects_InstituteProjectId"
        FOREIGN KEY ("InstituteProjectId") REFERENCES "InstituteProjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InstituteProjectPersonas_AIPersonas_PersonaId"
        FOREIGN KEY ("PersonaId") REFERENCES "AIPersonas" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_InstituteProjectPersonas_InstituteProjectId_PersonaId"
    ON "InstituteProjectPersonas" ("InstituteProjectId", "PersonaId");
CREATE INDEX IF NOT EXISTS "IX_InstituteProjectPersonas_PersonaId"
    ON "InstituteProjectPersonas" ("PersonaId");


-- 3. PersonaChatHistory  (side-persona chats; CustomerChatHistory stays the main-persona chat)
--    Mirrors CustomerChatHistory (no FK on StudentId there either) plus PersonaId.
CREATE TABLE IF NOT EXISTS "PersonaChatHistory" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StudentId"   integer NOT NULL,
    "SprintId"    integer NOT NULL,
    "PersonaId"   integer NOT NULL,
    "Role"        character varying(50) NOT NULL,
    "Message"     text NOT NULL,
    "AIModelName" character varying(100) NULL,
    "CreatedAt"   timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_PersonaChatHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PersonaChatHistory_AIPersonas_PersonaId"
        FOREIGN KEY ("PersonaId") REFERENCES "AIPersonas" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_PersonaChatHistory_StudentId_PersonaId_SprintId"
    ON "PersonaChatHistory" ("StudentId", "PersonaId", "SprintId");


-- 4. AgentExercises  (the contract: endpoint and limits)
CREATE TABLE IF NOT EXISTS "AgentExercises" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Key"          character varying(100) NOT NULL,
    "Name"         character varying(200) NOT NULL,
    "EndpointPath" character varying(200) NOT NULL,
    "LimitsJson"   text NULL,
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AgentExercises" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AgentExercises_Key" ON "AgentExercises" ("Key");


-- 5. AgentRequirements  (what students must discover, and which persona reveals it)
CREATE TABLE IF NOT EXISTS "AgentRequirements" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ExerciseId" integer NOT NULL,
    "Code"       character varying(20) NOT NULL,
    "Text"       text NOT NULL,
    "PersonaId"  integer NULL,
    CONSTRAINT "PK_AgentRequirements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AgentRequirements_AgentExercises_ExerciseId"
        FOREIGN KEY ("ExerciseId") REFERENCES "AgentExercises" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AgentRequirements_AIPersonas_PersonaId"
        FOREIGN KEY ("PersonaId") REFERENCES "AIPersonas" ("Id") ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AgentRequirements_ExerciseId_Code" ON "AgentRequirements" ("ExerciseId", "Code");
CREATE INDEX IF NOT EXISTS "IX_AgentRequirements_PersonaId" ON "AgentRequirements" ("PersonaId");


-- 6. AgentWorlds  (simulated Maps/Places data served by the proxy in fixture mode)
CREATE TABLE IF NOT EXISTS "AgentWorlds" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Key"       character varying(100) NOT NULL,
    "Name"      character varying(200) NOT NULL,
    "DataJson"  text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AgentWorlds" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AgentWorlds_Key" ON "AgentWorlds" ("Key");


-- 7. AgentScenarioSets  (versioned bundle; published sets are never edited, only re-versioned)
CREATE TABLE IF NOT EXISTS "AgentScenarioSets" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ExerciseId"  integer NOT NULL,
    "WorldId"     integer NOT NULL,
    "Name"        character varying(200) NOT NULL,
    "Version"     integer NOT NULL DEFAULT 1,
    "Status"      character varying(20) NOT NULL DEFAULT 'draft',
    "CreatedAt"   timestamp with time zone NOT NULL DEFAULT now(),
    "PublishedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_AgentScenarioSets" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AgentScenarioSets_Status" CHECK ("Status" IN ('draft', 'published', 'archived')),
    CONSTRAINT "FK_AgentScenarioSets_AgentExercises_ExerciseId"
        FOREIGN KEY ("ExerciseId") REFERENCES "AgentExercises" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AgentScenarioSets_AgentWorlds_WorldId"
        FOREIGN KEY ("WorldId") REFERENCES "AgentWorlds" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AgentScenarioSets_ExerciseId_Name_Version"
    ON "AgentScenarioSets" ("ExerciseId", "Name", "Version");
CREATE INDEX IF NOT EXISTS "IX_AgentScenarioSets_WorldId" ON "AgentScenarioSets" ("WorldId");


-- 8. AgentScenarios  (one test case; expectations tagged with requirement codes)
CREATE TABLE IF NOT EXISTS "AgentScenarios" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ScenarioSetId"    integer NOT NULL,
    "Key"              character varying(100) NOT NULL,
    "Request"          text NOT NULL,
    "PositionLat"      double precision NULL,
    "PositionLng"      double precision NULL,
    "ExpectationsJson" text NOT NULL,
    "SortOrder"        integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AgentScenarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AgentScenarios_AgentScenarioSets_ScenarioSetId"
        FOREIGN KEY ("ScenarioSetId") REFERENCES "AgentScenarioSets" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AgentScenarios_ScenarioSetId_Key" ON "AgentScenarios" ("ScenarioSetId", "Key");


-- 9. ProjectAgentScenarioSets  (project <-> set; at most one practice and one graded set per project)
CREATE TABLE IF NOT EXISTS "ProjectAgentScenarioSets" (
    "Id"                 integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "InstituteProjectId" integer NOT NULL,
    "ScenarioSetId"      integer NOT NULL,
    "Purpose"            character varying(20) NOT NULL,
    "CreatedAt"          timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ProjectAgentScenarioSets" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_ProjectAgentScenarioSets_Purpose" CHECK ("Purpose" IN ('practice', 'graded')),
    CONSTRAINT "FK_ProjectAgentScenarioSets_InstituteProjects_InstituteProjectId"
        FOREIGN KEY ("InstituteProjectId") REFERENCES "InstituteProjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectAgentScenarioSets_AgentScenarioSets_ScenarioSetId"
        FOREIGN KEY ("ScenarioSetId") REFERENCES "AgentScenarioSets" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProjectAgentScenarioSets_InstituteProjectId_Purpose"
    ON "ProjectAgentScenarioSets" ("InstituteProjectId", "Purpose");
CREATE INDEX IF NOT EXISTS "IX_ProjectAgentScenarioSets_ScenarioSetId" ON "ProjectAgentScenarioSets" ("ScenarioSetId");


-- 10. AgentGradingReports  (saved results; no FK on BoardId so grades survive board deletion)
CREATE TABLE IF NOT EXISTS "AgentGradingReports" (
    "Id"              integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GradingId"       character varying(32) NOT NULL,
    "BoardId"         character varying(50) NOT NULL,
    "ScenarioSetId"   integer NOT NULL,
    "Status"          character varying(20) NOT NULL,
    "Score"           integer NULL,
    "CriticalFailure" boolean NULL,
    "ReportJson"      text NULL,
    "StartedAt"       timestamp with time zone NOT NULL DEFAULT now(),
    "FinishedAt"      timestamp with time zone NULL,
    CONSTRAINT "PK_AgentGradingReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AgentGradingReports_AgentScenarioSets_ScenarioSetId"
        FOREIGN KEY ("ScenarioSetId") REFERENCES "AgentScenarioSets" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AgentGradingReports_GradingId" ON "AgentGradingReports" ("GradingId");
CREATE INDEX IF NOT EXISTS "IX_AgentGradingReports_BoardId" ON "AgentGradingReports" ("BoardId");
CREATE INDEX IF NOT EXISTS "IX_AgentGradingReports_ScenarioSetId" ON "AgentGradingReports" ("ScenarioSetId");

COMMIT;


-- =============================================================================
-- Verify (expect 9 tables and 1 column)
-- =============================================================================
-- SELECT table_name FROM information_schema.tables
--  WHERE table_name IN ('InstituteProjectPersonas','PersonaChatHistory','AgentExercises','AgentRequirements',
--                       'AgentWorlds','AgentScenarioSets','AgentScenarios','ProjectAgentScenarioSets','AgentGradingReports');
-- SELECT column_name FROM information_schema.columns
--  WHERE table_name = 'InstituteProjects' AND column_name = 'MainAIPersonaId';


-- =============================================================================
-- R. ROLLBACK  (drops everything above; run only if you need to undo)
-- =============================================================================
-- BEGIN;
-- DROP TABLE IF EXISTS "AgentGradingReports";
-- DROP TABLE IF EXISTS "ProjectAgentScenarioSets";
-- DROP TABLE IF EXISTS "AgentScenarios";
-- DROP TABLE IF EXISTS "AgentScenarioSets";
-- DROP TABLE IF EXISTS "AgentWorlds";
-- DROP TABLE IF EXISTS "AgentRequirements";
-- DROP TABLE IF EXISTS "AgentExercises";
-- DROP TABLE IF EXISTS "PersonaChatHistory";
-- DROP TABLE IF EXISTS "InstituteProjectPersonas";
-- ALTER TABLE "InstituteProjects" DROP CONSTRAINT IF EXISTS "FK_InstituteProjects_AIPersonas_MainAIPersonaId";
-- DROP INDEX IF EXISTS "IX_InstituteProjects_MainAIPersonaId";
-- ALTER TABLE "InstituteProjects" DROP COLUMN IF EXISTS "MainAIPersonaId";
-- COMMIT;
