-- =============================================================================
-- AIPersonas + Institutes.MainAIPersonaId  (PostgreSQL)
--
-- Adds the student-facing AI chat persona catalog and the per-institute selection.
-- Matches Migrations/20260815120000_AddPersonasAndInstituteMainAIPersona.cs.
--
-- Safe to re-run: every statement is guarded.
-- Behaviour before any institute selects a persona is unchanged — the chat keeps
-- using PromptConfig:Customer:SystemPrompt from appsettings.json and the "Customer" label.
--
-- ALREADY RAN THE EARLIER VERSION (table created as "Personas")? Skip section 1 and
-- run section 0 instead.
-- =============================================================================


-- 0. RENAME PATH — only if you already created the table as "Personas" ---------
-- Constraint names do not follow a table rename in Postgres, so they are renamed
-- explicitly. EF does not read constraint names at runtime; this is for tidiness.

-- ALTER TABLE "Personas" RENAME TO "AIPersonas";
-- ALTER TABLE "AIPersonas" RENAME CONSTRAINT "PK_Personas" TO "PK_AIPersonas";
-- ALTER TABLE "Institutes" RENAME CONSTRAINT "FK_Institutes_Personas_MainAIPersonaId"
--                                          TO "FK_Institutes_AIPersonas_MainAIPersonaId";


BEGIN;

-- 1. AIPersonas catalog -------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AIPersonas" (
    "Id"     integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name"   character varying(100) NOT NULL,
    "Prompt" text NULL,
    CONSTRAINT "PK_AIPersonas" PRIMARY KEY ("Id")
);

-- 2. Institutes.MainAIPersonaId ----------------------------------------------
ALTER TABLE "Institutes"
    ADD COLUMN IF NOT EXISTS "MainAIPersonaId" integer NULL;

CREATE INDEX IF NOT EXISTS "IX_Institutes_MainAIPersonaId"
    ON "Institutes" ("MainAIPersonaId");

-- ON DELETE SET NULL: deleting a persona must not delete the institute, it just
-- drops back to the configured prompt and the default label.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Institutes_AIPersonas_MainAIPersonaId'
    ) THEN
        ALTER TABLE "Institutes"
            ADD CONSTRAINT "FK_Institutes_AIPersonas_MainAIPersonaId"
            FOREIGN KEY ("MainAIPersonaId") REFERENCES "AIPersonas" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

COMMIT;


-- =============================================================================
-- Seed the persona rows.
--
-- Store the name WITHOUT an "AI " prefix — the code adds it where needed, so a row
-- named "AI Professor" would render as "AI AI Professor" in the LLM alias block.
-- A row named exactly "Customer" deliberately produces no alias block at all: it is
-- the platform default, so nothing needs renaming for it.
--
-- Prompt is filled in manually afterwards.
-- =============================================================================

-- INSERT INTO "AIPersonas" ("Name") VALUES ('Customer'), ('Professor');

-- Point an institute at a persona (labels + prompt follow immediately):
-- UPDATE "Institutes" SET "MainAIPersonaId" = (SELECT "Id" FROM "AIPersonas" WHERE "Name" = 'Professor')
-- WHERE "Id" = <instituteId>;

-- Clear the selection (back to appsettings prompt + "Customer" label):
-- UPDATE "Institutes" SET "MainAIPersonaId" = NULL WHERE "Id" = <instituteId>;
