-- =============================================================================
-- Personas + Institutes.MainAIPersonaId  (PostgreSQL)
--
-- Adds the student-facing AI chat persona catalog and the per-institute selection.
-- Matches Migrations/20260815120000_AddPersonasAndInstituteMainAIPersona.cs.
--
-- Safe to re-run: every statement is guarded.
-- Behaviour before any institute selects a persona is unchanged — the chat keeps
-- using PromptConfig:Customer:SystemPrompt from appsettings.json and the "Customer" label.
-- =============================================================================

BEGIN;

-- 1. Personas catalog ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Personas" (
    "Id"     integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name"   character varying(100) NOT NULL,
    "Prompt" text NULL,
    CONSTRAINT "PK_Personas" PRIMARY KEY ("Id")
);

-- 2. Institutes.MainAIPersonaId ----------------------------------------------
ALTER TABLE "Institutes"
    ADD COLUMN IF NOT EXISTS "MainAIPersonaId" integer NULL;

CREATE INDEX IF NOT EXISTS "IX_Institutes_MainAIPersonaId"
    ON "Institutes" ("MainAIPersonaId");

-- ON DELETE SET NULL: deleting a persona must not delete the institute, it just
-- drops back to the configured prompt and the default label.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Institutes_Personas_MainAIPersonaId'
    ) THEN
        ALTER TABLE "Institutes"
            ADD CONSTRAINT "FK_Institutes_Personas_MainAIPersonaId"
            FOREIGN KEY ("MainAIPersonaId") REFERENCES "Personas" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

COMMIT;


-- =============================================================================
-- Seed the existing customer persona (optional — run once, then paste the prompt).
--
-- Paste the current PromptConfig:Customer:SystemPrompt value from appsettings.json
-- into "Prompt" below. Until an institute is pointed at a persona row, nothing
-- changes: the code still falls back to appsettings.
-- =============================================================================

-- INSERT INTO "Personas" ("Name", "Prompt")
-- VALUES ('Customer', 'You are the ''AI Customer,'' the non-technical founder ... (paste here; double any single quotes)');

-- INSERT INTO "Personas" ("Name", "Prompt")
-- VALUES ('Professor', 'You are the ''AI Professor'' ... ');

-- Point an institute at a persona (labels + prompt follow immediately):
-- UPDATE "Institutes" SET "MainAIPersonaId" = (SELECT "Id" FROM "Personas" WHERE "Name" = 'Professor')
-- WHERE "Id" = <instituteId>;

-- Clear the selection (back to appsettings prompt + "Customer" label):
-- UPDATE "Institutes" SET "MainAIPersonaId" = NULL WHERE "Id" = <instituteId>;
