-- Manual PostgreSQL script equivalent to migration 20260411120000_AddCacheReviewTable.
-- Apply only if you are not using `dotnet ef database update`.

CREATE TABLE IF NOT EXISTS "CacheReview" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BoardId" character varying(50) NOT NULL,
    "StudentId" integer NOT NULL,
    "SprintNumber" integer NOT NULL,
    "SequenceNumber" integer NOT NULL,
    "Type" character varying(20) NOT NULL,
    "ReviewContent" text NOT NULL,
    CONSTRAINT "PK_CacheReview" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CacheReview_ProjectBoards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "ProjectBoards" ("BoardId") ON DELETE CASCADE,
    CONSTRAINT "FK_CacheReview_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_CacheReview_BoardId" ON "CacheReview" ("BoardId");
CREATE INDEX IF NOT EXISTS "IX_CacheReview_StudentId" ON "CacheReview" ("StudentId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CacheReview_BoardId_StudentId_SprintNumber_SequenceNumber"
    ON "CacheReview" ("BoardId", "StudentId", "SprintNumber", "SequenceNumber");

-- Type values used by EF: 'Resource' | 'Skill' | 'PR' (enum CacheReviewType stored as string).
-- Example: next SequenceNumber for a (BoardId, StudentId, SprintNumber) group is typically
--   (SELECT COALESCE(MAX("SequenceNumber"), 0) + 1 FROM "CacheReview" cr WHERE ...).
