-- Splits institute-scoped module rows from ProjectModules into InstituteProjectModules (same Ids preserved).
-- Align with EF migration 20260504071926_InstituteProjectModules_SplitFromProjectModules.
-- Run in a transaction after backup; review row counts.

BEGIN;

CREATE TABLE IF NOT EXISTS "InstituteProjectModules" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "InstituteProjectId" INTEGER NOT NULL,
    "ModuleType" INTEGER NULL,
    "Title" VARCHAR(100) NULL,
    "Description" TEXT NULL,
    "Sequence" INTEGER NULL,
    "OriginalModuleId" INTEGER NULL,
    CONSTRAINT "PK_InstituteProjectModules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InstituteProjectModules_InstituteProjects_InstituteProjectId" FOREIGN KEY ("InstituteProjectId") REFERENCES "InstituteProjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InstituteProjectModules_ModuleTypes_ModuleType" FOREIGN KEY ("ModuleType") REFERENCES "ModuleTypes" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_InstituteProjectModules_InstituteProjectId" ON "InstituteProjectModules" ("InstituteProjectId");
CREATE INDEX IF NOT EXISTS "IX_InstituteProjectModules_InstituteProjectId_OriginalModuleId" ON "InstituteProjectModules" ("InstituteProjectId", "OriginalModuleId");
CREATE INDEX IF NOT EXISTS "IX_InstituteProjectModules_ModuleType" ON "InstituteProjectModules" ("ModuleType");
CREATE INDEX IF NOT EXISTS "IX_InstituteProjectModules_Sequence" ON "InstituteProjectModules" ("Sequence");

INSERT INTO "InstituteProjectModules" ("Id", "InstituteProjectId", "ModuleType", "Title", "Description", "Sequence", "OriginalModuleId")
SELECT "Id", "InstituteProjectId", "ModuleType", "Title", "Description", "Sequence", "OriginalModuleId"
FROM "ProjectModules"
WHERE "InstituteProjectId" IS NOT NULL;

SELECT setval(
  pg_get_serial_sequence('"InstituteProjectModules"', 'Id'),
  GREATEST((SELECT COALESCE(MAX("Id"), 0) FROM "InstituteProjectModules"), 1)
);

DELETE FROM "ProjectModules" WHERE "InstituteProjectId" IS NOT NULL;

ALTER TABLE "ProjectModules" DROP CONSTRAINT IF EXISTS "FK_ProjectModules_InstituteProjects_InstituteProjectId";
DROP INDEX IF EXISTS "IX_ProjectModules_InstituteProjectId";
ALTER TABLE "ProjectModules" DROP COLUMN IF EXISTS "InstituteProjectId";

COMMIT;
