-- Phase 1 schema: introduce InstituteSquads + InstituteSquadRoles,
-- and link InstituteTemplates to SquadId.

ALTER TABLE "InstituteTemplates"
ADD COLUMN IF NOT EXISTS "SquadId" integer NULL;

CREATE TABLE IF NOT EXISTS "InstituteSquads" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "InstituteId" integer NOT NULL,
  "Name" varchar(100) NOT NULL,
  "IsActive" boolean NOT NULL DEFAULT TRUE,
  "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" timestamptz NULL,
  CONSTRAINT "FK_InstituteSquads_Institutes_InstituteId"
    FOREIGN KEY ("InstituteId") REFERENCES "Institutes"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "InstituteSquadRoles" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SquadId" integer NOT NULL,
  "BaseInstituteRoleId" integer NULL,
  "Name" varchar(100) NOT NULL,
  "Description" varchar(500) NULL,
  "Competencies" text NULL,
  "Category" varchar(50) NULL,
  "Type" integer NOT NULL DEFAULT 0,
  "SkillId" integer NULL,
  "CustomerEngagement" boolean NOT NULL DEFAULT FALSE,
  "IsTechnical" boolean NOT NULL DEFAULT FALSE,
  "IsActive" boolean NOT NULL DEFAULT TRUE,
  "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" timestamptz NULL,
  CONSTRAINT "FK_InstituteSquadRoles_InstituteSquads_SquadId"
    FOREIGN KEY ("SquadId") REFERENCES "InstituteSquads"("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_InstituteSquadRoles_InstituteRoles_BaseInstituteRoleId"
    FOREIGN KEY ("BaseInstituteRoleId") REFERENCES "InstituteRoles"("Id") ON DELETE SET NULL,
  CONSTRAINT "FK_InstituteSquadRoles_RoleTypes_Type"
    FOREIGN KEY ("Type") REFERENCES "RoleTypes"("Id") ON DELETE RESTRICT,
  CONSTRAINT "FK_InstituteSquadRoles_Skills_SkillId"
    FOREIGN KEY ("SkillId") REFERENCES "Skills"("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_InstituteTemplates_SquadId"
  ON "InstituteTemplates" ("SquadId");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquads_InstituteId"
  ON "InstituteSquads" ("InstituteId");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquads_InstituteId_Name"
  ON "InstituteSquads" ("InstituteId", "Name");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquadRoles_SquadId"
  ON "InstituteSquadRoles" ("SquadId");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquadRoles_SquadId_Name"
  ON "InstituteSquadRoles" ("SquadId", "Name");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquadRoles_BaseInstituteRoleId"
  ON "InstituteSquadRoles" ("BaseInstituteRoleId");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquadRoles_Type"
  ON "InstituteSquadRoles" ("Type");
CREATE INDEX IF NOT EXISTS "IX_InstituteSquadRoles_SkillId"
  ON "InstituteSquadRoles" ("SkillId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'FK_InstituteTemplates_InstituteSquads_SquadId'
  ) THEN
    ALTER TABLE "InstituteTemplates"
    ADD CONSTRAINT "FK_InstituteTemplates_InstituteSquads_SquadId"
      FOREIGN KEY ("SquadId") REFERENCES "InstituteSquads"("Id") ON DELETE SET NULL;
  END IF;
END $$;
