-- InstituteRoles: same columns as Roles + InstituteId (FK Institutes). Copy all global Roles for InstituteId = 1.
-- Option A (recommended): apply EF migration 20260421120000_AddInstituteRolesTable, then run only the INSERT block at the bottom.
-- Option B: run this full script on a DB that has "Institutes", "RoleTypes", and "Roles" but not yet "InstituteRoles".

BEGIN;

-- ---------------------------------------------------------------------------
-- Schema (skip if you already applied the EF migration)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "InstituteRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InstituteId" integer NOT NULL,
    "TemplateId" integer NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NULL,
    "Category" character varying(50) NULL,
    "Type" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_InstituteRoles" PRIMARY KEY ("Id")
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_InstituteRoles_Institutes_InstituteId'
    ) THEN
        ALTER TABLE "InstituteRoles"
            ADD CONSTRAINT "FK_InstituteRoles_Institutes_InstituteId"
            FOREIGN KEY ("InstituteId") REFERENCES "Institutes" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_InstituteRoles_RoleTypes_Type'
    ) THEN
        ALTER TABLE "InstituteRoles"
            ADD CONSTRAINT "FK_InstituteRoles_RoleTypes_Type"
            FOREIGN KEY ("Type") REFERENCES "RoleTypes" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_InstituteRoles_InstituteTemplates_TemplateId'
    ) THEN
        ALTER TABLE "InstituteRoles"
            ADD CONSTRAINT "FK_InstituteRoles_InstituteTemplates_TemplateId"
            FOREIGN KEY ("TemplateId") REFERENCES "InstituteTemplates" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_InstituteRoles_InstituteId" ON "InstituteRoles" ("InstituteId");
CREATE INDEX IF NOT EXISTS "IX_InstituteRoles_Type" ON "InstituteRoles" ("Type");
CREATE INDEX IF NOT EXISTS "IX_InstituteRoles_TemplateId" ON "InstituteRoles" ("TemplateId");

-- ---------------------------------------------------------------------------
-- Data: one row per "Roles" row for InstituteId = 1 (new Ids; no "Id" from Roles)
-- Idempotent: skip if a row for the same institute + name already exists.
-- ---------------------------------------------------------------------------
INSERT INTO "InstituteRoles" ("InstituteId", "Name", "Description", "Category", "Type", "IsActive", "CreatedAt", "UpdatedAt")
SELECT
    1,
    r."Name",
    r."Description",
    r."Category",
    r."Type",
    r."IsActive",
    r."CreatedAt",
    r."UpdatedAt"
FROM "Roles" r
WHERE NOT EXISTS (
    SELECT 1
    FROM "InstituteRoles" ir
    WHERE ir."InstituteId" = 1
      AND ir."Name" = r."Name"
);

-- If you applied the data only via EF and need to register the migration:
-- INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
-- VALUES ('20260421120000_AddInstituteRolesTable', '8.0.0')
-- ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
