-- Institutes table shaped like Organizations (+ State, Country)
-- plus Students.InstituteId (nullable FK) and one seed row.
-- PostgreSQL.
--
-- To drop and recreate "Institutes" (must drop FK first), run:
--   Scripts/DropInstitutes_for_recreate.sql
-- then run this script again.

-- === CREATE / UPGRADE (idempotent where noted) ================================

CREATE TABLE IF NOT EXISTS "Institutes"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500) NULL,
    "Website" character varying(100) NULL,
    "ContactEmail" character varying(255) NULL,
    "Phone" character varying(20) NULL,
    "Type" character varying(50) NULL,
    "Address" character varying(200) NULL,
    "State" character varying(100) NULL,
    "Country" character varying(100) NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "Logo" text NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NULL,
    "TermsUse" text NULL,
    "TermsAccepted" boolean NOT NULL DEFAULT FALSE,
    "TermsAcceptedAt" timestamp with time zone NULL,
    "PasswordHash" character varying(256) NULL
);

INSERT INTO "Institutes"
    ("Id", "Name", "Description", "Website", "ContactEmail", "Phone", "Type", "Address", "State", "Country", "IsActive", "TermsAccepted")
VALUES
    (1,
     'StrAppers Academy of Technology',
     'Technology-focused institute and applied learning campus.',
     'https://academy.strappers.example.org',
     'contact@strappers-academy.example.org',
     '555-2100',
     'Institute',
     '42 Innovation Way, Suite 100',
     'Tel Aviv District',
     'Israel',
     TRUE,
     FALSE)
ON CONFLICT ("Id") DO NOTHING;

ALTER TABLE "Students"
    ADD COLUMN IF NOT EXISTS "InstituteId" integer NULL;

CREATE INDEX IF NOT EXISTS "IX_Students_InstituteId"
    ON "Students" ("InstituteId");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_Students_Institutes_InstituteId')
    THEN
        ALTER TABLE "Students"
            ADD CONSTRAINT "FK_Students_Institutes_InstituteId"
            FOREIGN KEY ("InstituteId") REFERENCES "Institutes" ("Id")
            ON DELETE SET NULL;
    END IF;
END $$;
