-- Manual PostgreSQL script: Metrics catalog + CacheMetrics (matches EF migration AddMetricsAndCacheMetricsTables).
-- Use when not applying migrations via dotnet ef database update.

CREATE TABLE IF NOT EXISTS "Metrics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Endpoint" character varying(100) NULL,
    CONSTRAINT "PK_Metrics" PRIMARY KEY ("Id")
);

INSERT INTO "Metrics" ("Id", "Name", "Endpoint") VALUES
    (1, 'Adherence', NULL),
    (2, 'GapAnalysis', NULL),
    (3, 'Improvement', NULL),
    (4, 'Communication', NULL),
    (5, 'Attendance', NULL),
    (6, 'Strengths&weaknesses', NULL),
    (7, 'CustomerEngagement', NULL)
ON CONFLICT ("Id") DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('"Metrics"', 'Id'),
    GREATEST((SELECT COALESCE(MAX("Id"), 1) FROM "Metrics"), 1));

CREATE TABLE IF NOT EXISTS "CacheMetrics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BoardId" character varying(50) NOT NULL,
    "StudentId" integer NOT NULL,
    "SprintNumber" integer NOT NULL,
    "MetricId" integer NOT NULL,
    "ReviewContent" text NOT NULL,
    "Graph" text NULL,
    CONSTRAINT "PK_CacheMetrics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CacheMetrics_Metrics_MetricId" FOREIGN KEY ("MetricId") REFERENCES "Metrics" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CacheMetrics_ProjectBoards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "ProjectBoards" ("BoardId") ON DELETE CASCADE,
    CONSTRAINT "FK_CacheMetrics_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_CacheMetrics_BoardId" ON "CacheMetrics" ("BoardId");
CREATE INDEX IF NOT EXISTS "IX_CacheMetrics_MetricId" ON "CacheMetrics" ("MetricId");
CREATE INDEX IF NOT EXISTS "IX_CacheMetrics_StudentId" ON "CacheMetrics" ("StudentId");
