-- Create Skills lookup and add SkillId + CustomerEngagement to Roles/InstituteRoles.
-- Matches migration: 20260422190000_AddSkillsAndRoleSkillColumns (column name: "SkillId").

BEGIN;

CREATE TABLE IF NOT EXISTS "Skills" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    CONSTRAINT "PK_Skills" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Skills_Name" ON "Skills" ("Name");

-- Optional: seed skills (edit names as needed). Example:
-- INSERT INTO "Skills" ("Name") VALUES ('Engineering'), ('Design'), ('Product')
-- ON CONFLICT ("Name") DO NOTHING;

ALTER TABLE "Roles"
    ADD COLUMN IF NOT EXISTS "SkillId" integer;

ALTER TABLE "Roles"
    ADD COLUMN IF NOT EXISTS "CustomerEngagement" boolean NOT NULL DEFAULT false;

ALTER TABLE "InstituteRoles"
    ADD COLUMN IF NOT EXISTS "SkillId" integer;

ALTER TABLE "InstituteRoles"
    ADD COLUMN IF NOT EXISTS "CustomerEngagement" boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "IX_Roles_SkillId" ON "Roles" ("SkillId");
CREATE INDEX IF NOT EXISTS "IX_InstituteRoles_SkillId" ON "InstituteRoles" ("SkillId");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Roles_Skills_SkillId'
    ) THEN
        ALTER TABLE "Roles"
            ADD CONSTRAINT "FK_Roles_Skills_SkillId"
            FOREIGN KEY ("SkillId") REFERENCES "Skills" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_InstituteRoles_Skills_SkillId'
    ) THEN
        ALTER TABLE "InstituteRoles"
            ADD CONSTRAINT "FK_InstituteRoles_Skills_SkillId"
            FOREIGN KEY ("SkillId") REFERENCES "Skills" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

-- Optional: register migration when applied manually.
-- INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
-- VALUES ('20260422190000_AddSkillsAndRoleSkillColumns', '8.0.0')
-- ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
