-- Teachers: institute staff logins (email + password). FK to Institutes.
-- Run after Institutes exists. PostgreSQL.

CREATE TABLE IF NOT EXISTS "Teachers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InstituteId" integer NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(256) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Teachers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Teachers_Institutes_InstituteId" FOREIGN KEY ("InstituteId") REFERENCES "Institutes" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Teachers_Email" ON "Teachers" ("Email");
CREATE INDEX IF NOT EXISTS "IX_Teachers_InstituteId" ON "Teachers" ("InstituteId");
