-- TrelloTemplates: institute-scoped Task Builder template saves (FK Institutes, Projects).
-- Run on PostgreSQL after deploying schema.

CREATE TABLE IF NOT EXISTS "TrelloTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InstituteId" integer NOT NULL,
    "ProjectId" integer NOT NULL,
    "TrelloBoardJson" text NOT NULL,
    CONSTRAINT "PK_TrelloTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TrelloTemplates_Institutes_InstituteId" FOREIGN KEY ("InstituteId") REFERENCES "Institutes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TrelloTemplates_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TrelloTemplates_InstituteId" ON "TrelloTemplates" ("InstituteId");
CREATE INDEX IF NOT EXISTS "IX_TrelloTemplates_ProjectId" ON "TrelloTemplates" ("ProjectId");
CREATE INDEX IF NOT EXISTS "IX_TrelloTemplates_InstituteId_ProjectId" ON "TrelloTemplates" ("InstituteId", "ProjectId");
